targets:
  $default:
    builders:
      json_serializable:
        options:
          # https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable-class.html
#          any_map: false
#          checked: false
#          create_factory: true
#          create_to_json: true
#          disallow_unrecognized_keys: false
#          explicit_to_json: false
          field_rename: snake
#          ignore_unannotated: false
#          include_if_null: true
#          nullable: true
