name: kyouen_vs_flutter
description: Kyouen app for versus mode.

version: 1.0.0+1

environment:
  sdk: ">=2.13.1 <3.0.0"
  flutter: ^2.2.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.2.0
  firebase_analytics: ^8.1.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  provider: ^5.0.0
  equatable: ^2.0.0
  rxdart: ^0.27.1
  freezed_annotation: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  freezed: ^0.14.0+1
  json_serializable: ^4.0.2
  pedantic_mono: any

flutter:
  uses-material-design: true
